[package]
name = "imnodes-wgpu-examples"
version = "0.1.0"
authors = ["Benedikt Mandelkow <benedikt.mandelkow@rwth-aachen.de>", "imgui-wgpu contributors"]
edition = "2021"

[dependencies]
imnodes = { path = "../" }

wgpu = "0.15.1"
winit = {version = "0.27.1", features = ["x11"] }
futures = "0.3.21"
imgui = "0.10.0"
imgui-winit-support = { version = "0.10.0" }
imgui-wgpu = "0.22.0"
